BE-U1-W2-D5/Models/ErrorViewModel.cs
namespace BE_U1_W2_D5.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BE-U1-W2-D5/Models/RepositoryObject.cs
namespace BE_U1_W2_D5.Models
{
    public static class RepositoryObject
    {
        public static List<Scarpa> _scarpe;
        public static List<Scarpa> GetAll()
        {

            return _scarpe;
        }

        public static void SaveScarpa(Scarpa scarpa)
        {
            _scarpe.Add(scarpa);
        }
    }
}

BE-U1-W2-D5/Models/Scarpa.cs
namespace BE_U1_W2_D5.Models
{
    public class Scarpa
    {

        public Guid Id { get; set; } 
        public string NomeArticolo { get; set; }
        public decimal Prezzo { get; set; }

        public string Descrizione { get; set; }

        public string ImmagineDiCopertina { get; set; }

        public string ImmagineAggiuntiva { get; set; }

        public string ImmagineAggiuntiva2 { get; set; }

        public string Logo { get; set; }


    }
}

BE-U1-W2-D5/ViewModels/ScarpaViewModel.cs
namespace BE_U1_W2_D5.ViewModels
{
    public class ScarpaViewModel
    {
    }
}

BE-U1-W2-D5/Controllers/DettaglioController.cs
using BE_U1_W2_D5.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BE_U1_W2_D5.Controllers
{
    public class DettaglioController : Controller
    {

        [HttpGet("{id:guid}")]
        public IActionResult Dettaglio(Guid id)
        {

            //var Dettaglio = List.Find(id);
            return View(id);
        }
    }
}

BE-U1-W2-D5/Controllers/HomeController.cs
using System.Diagnostics;
using BE_U1_W2_D5.Models;
using Microsoft.AspNetCore.Mvc;

namespace BE_U1_W2_D5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BE-U1-W2-D5/Controllers/RepositoryObjectController.cs
using BE_U1_W2_D5.Models;
using Microsoft.AspNetCore.Mvc;

namespace BE_U1_W2_D5.Controllers
{
    public class RepositoryObjectController : Controller
    {
        public IActionResult Index()
        {
            var listaScarpe = RepositoryObject.GetAll();
            return View(listaScarpe);
        }
        public IActionResult Dettaglio(string id)
        {
            return RedirectToAction("Dettaglio", new { id = id });
        }
    }
}

BE-U1-W2-D5/Controllers/ScarpaController.cs
using BE_U1_W2_D5.Models;
using Microsoft.AspNetCore.Mvc;

namespace BE_U1_W2_D5.Controllers
{
    public class ScarpaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BE-U1-W2-D5/Views/Dettaglio/Dettaglio.cshtml
@model Guid
@{
    List<Scarpa> Dettagli = RepositoryObject.GetAll();
    Scarpa scarpa = Dettagli.Find(S => S.Id == Model);

}

<div class="container dettaglio">
    <div class="row">
        <div class="col-md-8 d-flex align-items-start justify-content-center flex-wrap">
            <img src="@scarpa.ImmagineDiCopertina" alt="Alternate Text"/>
            <img src="@scarpa.ImmagineAggiuntiva" alt="Alternate Text"/>
            <img src="@scarpa.ImmagineAggiuntiva2" alt="Alternate Text"/>
            <img src="@scarpa.Logo" alt="Alternate Text" />
        </div>
        <div class="col-md-4">
            <h3>@scarpa.NomeArticolo</h3>
            <p>@scarpa.Descrizione</p>
            <p>@scarpa.Prezzo € </p>

            <p>3 pagamenti da @(Math.Round(scarpa.Prezzo / 3, 2)) € a interessi 0% con Klarna. Scopri di più </p>
            <p>
                Paga in 3 rate da @(Math.Round(scarpa.Prezzo / 3, 2)) € senza interessi con PayPal. TAEG 0%. Scopri di più.
            </p>

        </div>
    </div>
</div>

BE-U1-W2-D5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    RepositoryObject._scarpe = new();
    Scarpa s1 = new Scarpa()
    {
        Id = Guid.NewGuid(),
        NomeArticolo = "Adidas Handball Spezial",
        Prezzo = 89.00m,
        Descrizione = "Scarpa da ginnastica colore rosa",
        ImmagineDiCopertina = "https://assets.footlocker.com/is/image/FLDM/316706221104_02?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva = "https://assets.footlocker.com/is/image/FLDM/316706221104_03?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva2 = "https://assets.footlocker.com/is/image/FLDM/316706221104_07?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        Logo = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Original_Adidas_logo.svg/768px-Original_Adidas_logo.svg.png"
    };
    RepositoryObject.SaveScarpa(s1);
    Scarpa s2 = new Scarpa()
    {

        Id = Guid.NewGuid(),
        NomeArticolo = "Nike Air Force 1 Low",
        Prezzo = 109.00m,
        Descrizione = "Scarpa da ginnastica colore bianco",
        ImmagineDiCopertina = "https://assets.footlocker.com/is/image/FLDM/316705874804_03?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva = "https://assets.footlocker.com/is/image/FLDM/316475363004_03?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva2 = "https://assets.footlocker.com/is/image/FLDM/316475363004_07?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        Logo = "https://cdn.freebiesupply.com/logos/large/2x/nike-4-logo-png-transparent.png"
    };
    RepositoryObject.SaveScarpa(s2);

    Scarpa s3 = new Scarpa()
    {

        Id = Guid.NewGuid(),
        NomeArticolo = "New Balance 530",
        Prezzo = 99.00m,
        Descrizione = "Scarpa da ginnastica colore marrone",
        ImmagineDiCopertina = "https://assets.footlocker.com/is/image/FLDM/316705653604_02?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva = "https://assets.footlocker.com/is/image/FLDM/316705653604_03?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva2 = "https://assets.footlocker.com/is/image/FLDM/316705653604_07?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        Logo = "https://www.pngall.com/wp-content/uploads/15/New-Balance-Logo-PNG-Photos.png"
    };
    RepositoryObject.SaveScarpa(s3);

    Scarpa s4 = new Scarpa()
    {

        Id = Guid.NewGuid(),
        NomeArticolo = "Adidas Campus 00s",
        Prezzo = 119.00m,
        Descrizione = "Scarpa da ginnastica colore verde",
        ImmagineDiCopertina = "https://assets.footlocker.com/is/image/FLDM/314310885604_02?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva = "https://assets.footlocker.com/is/image/FLDM/314310885604_03?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva2 = "https://assets.footlocker.com/is/image/FLDM/314310885604_07?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        Logo = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Original_Adidas_logo.svg/768px-Original_Adidas_logo.svg.png"
    };
    RepositoryObject.SaveScarpa(s4);


    List<Scarpa> scarpe = RepositoryObject.GetAll();
} 

<div class="text-center">
    <h1 class="display-4 text-center fs-1 font-main-color  fst-italic">Welcome to <span class="fw-bold">Scarpe & Co.</span></h1>
    <section>
        <div class="container banner" style="margin-top: 100px; margin-bottom:100px">
            <div class="row">
                <div class="col-md-7 font-main-color d-flex flex-column justify-content-center">
                    <h3 class="text-start">Scopri le nuove</h3>
                    <h2 style="font-size:6rem;">Adidas Spezial</h2>
                    <p>Scegli il tuo stile</p>
                    <div class="shoes-carousel d-flex align-items-center justify-content-evenly">
                        <img src="~/assets/img/adidas_spezial_pink_carousel.webp" alt="Alternate Text" />
                        <img src="~/assets/img/adidas_spezial_beige_carousel.webp" alt="Alternate Text" />
                        <img src="~/assets/img/adidas_spezial_black_carousel.webp" alt="Alternate Text" />
                        <img src="~/assets/img/adidas_spezial_blue_carousel.webp" alt="Alternate Text" />
                        <img src="~/assets/img/adidas_spezial_grey_carousel.webp" alt="Alternate Text" />
                        <img src="~/assets/img/adidas_spezial_olive_carousel.webp" alt="Alternate Text" />
                        <img src="~/assets/img/adidas_spezial_skyblue_carousel.webp" alt="Alternate Text" />
                        <img src="~/assets/img/adidas_spezial_winered_carousel.webp" alt="Alternate Text" />
                    </div>
                </div>
                <div class="col-md-5 d-flex flex-column justify-content-center">
                    <img src="~/assets/img/adidas_spezial_pink.webp" alt="Adidas Spezial Rosa" style="transform: rotate(-15deg); width:100%" />
                </div>
            </div>
        </div>
    </section>
    <section>
        <h3 class="font-main-color">Ultimi Arrivi</h3>
        <div class="row" style="background-color:#ffffff;">
            <div class="col-12 d-flex justify-content-evenly align-items-center flex-wrap">

                @foreach (Scarpa nomeOggetto in scarpe)
                {
                    <div class="card my-2" style="width: 18rem; height: 450px;">
                        <img src="@nomeOggetto.ImmagineDiCopertina" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@nomeOggetto.NomeArticolo</h5>
                            <p class="card-text text-truncate">@nomeOggetto.Descrizione</p>
                            <a asp-controller="Dettaglio" asp-action="Dettaglio" asp-route-id="@nomeOggetto.Id" class="btn btn-primary">Dettagli</a>
                        </div>
                    </div>
                }

            </div>
        </div>
    </section>
    
</div>

BE-U1-W2-D5/Views/RepositoryObject/Index.cshtml
@model List<Scarpa>
@{
   

    Scarpa s5 = new Scarpa()
    {

        Id = Guid.NewGuid(),
        NomeArticolo = "Puma Palermo",
        Prezzo = 99.00m,
        Descrizione = "Scarpa da ginnastica colore rosa",
        ImmagineDiCopertina = "https://assets.footlocker.com/is/image/FLDM/315349207902_02?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva = "https://assets.footlocker.com/is/image/FLDM/315349207902_03?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva2 = "https://assets.footlocker.com/is/image/FLDM/315349207902_07?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        Logo = "https://images.seeklogo.com/logo-png/28/2/puma-se-logo-png_seeklogo-287825.png"
    };
    RepositoryObject.SaveScarpa(s5);

    Scarpa s6 = new Scarpa()
    {

        Id = Guid.NewGuid(),
        NomeArticolo = "Converse Lift Hi",
        Prezzo = 105.00m,
        Descrizione = "Scarpa da ginnastica colore beige",
        ImmagineDiCopertina = "https://assets.footlocker.com/is/image/FLDM/315550531602_02?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva = "https://assets.footlocker.com/is/image/FLDM/315550531602_03?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva2 = "https://assets.footlocker.com/is/image/FLDM/315550531602_07?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        Logo = "https://logodix.com/logo/10350.png"
    };
    RepositoryObject.SaveScarpa(s6);

    Scarpa s7 = new Scarpa()
    {

        Id = Guid.NewGuid(),
        NomeArticolo = "Converse Pc2 Wntr",
        Prezzo = 100.00m,
        Descrizione = "Scarpa da ginnastica colore rosa",
        ImmagineDiCopertina = "https://assets.footlocker.com/is/image/FLDM/315550068902_02?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva = "https://assets.footlocker.com/is/image/FLDM/315550068902_03?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva2 = "https://assets.footlocker.com/is/image/FLDM/315550068902_07?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        Logo = "https://logodix.com/logo/10350.png"
    };
    RepositoryObject.SaveScarpa(s7);

    Scarpa s8 = new Scarpa()
    {

        Id = Guid.NewGuid(),
        NomeArticolo = "Adidas Samba",
        Prezzo = 80.00m,
        Descrizione = "Scarpa da ginnastica colore rosa",
        ImmagineDiCopertina = "https://assets.footlocker.com/is/image/FLDM/315349565002_02?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva = "https://assets.footlocker.com/is/image/FLDM/315349565002_03?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva2 = "https://assets.footlocker.com/is/image/FLDM/315349565002_07?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        Logo = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Original_Adidas_logo.svg/768px-Original_Adidas_logo.svg.png"
    };
    RepositoryObject.SaveScarpa(s8);

    Scarpa s9 = new Scarpa()
    {

        Id = Guid.NewGuid(),
        NomeArticolo = "Puma Palermo",
        Prezzo = 99.00m,
        Descrizione = "Scarpa da ginnastica colore panna",
        ImmagineDiCopertina = "https://assets.footlocker.com/is/image/FLDM/315349208702_02?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva = "https://assets.footlocker.com/is/image/FLDM/315349208702_03?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        ImmagineAggiuntiva2 = "https://assets.footlocker.com/is/image/FLDM/315349208702_07?fmt=webp-alpha&bfc=on&wid=500&hei=500",
        Logo = "https://images.seeklogo.com/logo-png/28/2/puma-se-logo-png_seeklogo-287825.png"
    };
    RepositoryObject.SaveScarpa(s9);

    

   
    

    List<Scarpa> scarpe = RepositoryObject.GetAll();

    if (scarpe.Count() == 0)
    {
        Console.WriteLine("Nessun articolo trovato");
    }
    else
    {

    }

}

<div class="container">
<div class="row justify-content-center d-flex">

    @foreach (var S in scarpe)
    {
        <div class="col-4 text-center">
        <div class="card my-2" style="width: 18rem; height: 450px;">
            <img src="@S.ImmagineDiCopertina" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">@S.NomeArticolo</h5>
                <p class="card-text text-truncate">@S.Descrizione</p>
<a asp-controller="Dettaglio" asp-action="Dettaglio" asp-route-id="@S.Id" class="btn btn-primary">Dettagli</a>
            </div>
            </div>
        </div>
    }
    </div>
</div>

BE-U1-W2-D5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BE_U1_W2_D5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BE_U1_W2_D5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @* <a class="navbar-brand fst-italic" asp-area="" asp-controller="Home" asp-action="Index">Scarpe & Co.</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-center">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link font-main-color" asp-area="" asp-controller="Home" asp-action="Index" style="font-weight: bold;">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-main-color" asp-area="" asp-controller="RepositoryObject" asp-action="Index" style="font-weight: bold;">Scarpe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-main-color" asp-area="" asp-controller="Home" asp-action="Privacy" style="font-weight: bold;">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container main">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Scarpe & Co. - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>